#!/usr/bin/env bash
# Per-boot runtime startup for the Monthly Capsule Cloud Agent environment.
# Brings up the Docker daemon, the local Supabase stack (Postgres + REST + Storage),
# and writes .env.local. Idempotent: safe to run on every boot and to re-run.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

echo "[start] Starting Docker daemon (if needed) ..."
if ! docker info >/dev/null 2>&1; then
  sudo nohup dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do
    if sudo docker info >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi
# Make the socket reachable without sudo/newgrp inside this session.
sudo chmod 666 /var/run/docker.sock || true
docker info >/dev/null

echo "[start] Fixing bridge networking for nested containers ..."
# Nested Cloud Agent VMs route bridged inter-container traffic through a broken
# nftables FORWARD path. Letting same-bridge traffic bypass netfilter fixes
# container-to-container connectivity (e.g. Supabase services reaching Postgres).
sudo modprobe br_netfilter 2>/dev/null || true
sudo sysctl -w net.bridge.bridge-nf-call-iptables=0 >/dev/null 2>&1 || true
sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0 >/dev/null 2>&1 || true

echo "[start] Starting local Supabase stack (applies migrations) ..."
supabase start

echo "[start] Writing .env.local ..."
# Preserve previously generated secrets across restarts; generate on first boot.
get_kept() { [ -f .env.local ] && grep -E "^$1=" .env.local | head -1 | cut -d= -f2- || true; }
COOKIE_SECRET="$(get_kept COOKIE_SECRET)"; [ -n "$COOKIE_SECRET" ] || COOKIE_SECRET="$(openssl rand -hex 32)"
CRON_SECRET="$(get_kept CRON_SECRET)"; [ -n "$CRON_SECRET" ] || CRON_SECRET="$(openssl rand -hex 16)"

eval "$(supabase status -o env | grep -E '^(API_URL|ANON_KEY|SERVICE_ROLE_KEY)=')"

cat > .env.local <<EOF
# Local development (gitignored). Regenerated by .cursor/start.sh on each boot.
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# Resend unset -> outbound email is skipped locally (email_sent_at stays null).
# RESEND_API_KEY=
# RESEND_FROM_EMAIL=

COOKIE_SECRET=${COOKIE_SECRET}
APP_URL=http://localhost:3000
CRON_SECRET=${CRON_SECRET}
CREATE_GROUP_CODE=plainandsimple
EOF

echo "[start] Ready. Supabase API: ${API_URL}"
